AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Campus Connect - Consolidated Serverless Backend with JWT Authorizer

Globals:
  Function:
    Timeout: 30
    Runtime: nodejs18.x
    MemorySize: 256
    Environment:
      Variables:
        USERS_TABLE: !Ref UsersTable
        PRODUCTS_TABLE: !Ref ProductsTable
        ORDERS_TABLE: !Ref OrdersTable
        CARTS_TABLE: !Ref CartsTable
        CATEGORIES_TABLE: !Ref CategoriesTable
        SUBCATEGORIES_TABLE: !Ref SubcategoriesTable
        UPLOADS_BUCKET: !Ref UploadsBucket
        JWT_SECRET: !Ref JWTSecret

Parameters:
  Environment:
    Type: String
    Default: dev
    AllowedValues: [dev, staging, prod]

Resources:
  # Lambda Layer with shared dependencies
  SharedLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: !Sub campus-connect-shared-${Environment}
      Description: Shared dependencies and utilities
      ContentUri: src/layers/shared/
      CompatibleRuntimes:
        - nodejs18.x
      RetentionPolicy: Delete

  # JWT Authorizer Function
  JWTAuthorizer:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub campus-connect-jwt-authorizer-${Environment}
      CodeUri: src/functions/auth/
      Handler: authorizer.handler
      Layers:
        - !Ref SharedLayer
      Policies:
        - Statement:
            - Effect: Allow
              Action: secretsmanager:GetSecretValue
              Resource: !Ref JWTSecret

  # =========================
  # CONSOLIDATED FUNCTIONS
  # =========================

  # Auth Function - handles all /auth/* routes
  AuthFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub campus-connect-auth-${Environment}
      CodeUri: src/functions/auth/
      Handler: index.handler
      Layers:
        - !Ref SharedLayer
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref UsersTable
        - Statement:
            - Effect: Allow
              Action: secretsmanager:GetSecretValue
              Resource: !Ref JWTSecret
      Events:
        RegisterApi:
          Type: Api
          Properties:
            Path: /auth/register
            Method: post
            RestApiId: !Ref CampusConnectApi
        LoginApi:
          Type: Api
          Properties:
            Path: /auth/login
            Method: post
            RestApiId: !Ref CampusConnectApi
        UpdateProfilePictureApi:
          Type: Api
          Properties:
            Path: /auth/profile/picture
            Method: put
            RestApiId: !Ref CampusConnectApi
            Auth:
              Authorizer: JWTAuth

  # Products Function - handles all /products/* routes
  ProductsFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub campus-connect-products-${Environment}
      CodeUri: src/functions/products/
      Handler: index.handler
      Layers:
        - !Ref SharedLayer
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref ProductsTable
        - DynamoDBReadPolicy:
            TableName: !Ref CategoriesTable
        - DynamoDBReadPolicy:
            TableName: !Ref SubcategoriesTable
        - DynamoDBReadPolicy:
            TableName: !Ref UsersTable
      Events:
        GetProductsApi:
          Type: Api
          Properties:
            Path: /products
            Method: get
            RestApiId: !Ref CampusConnectApi
        GetProductApi:
          Type: Api
          Properties:
            Path: /products/{id}
            Method: get
            RestApiId: !Ref CampusConnectApi
        CreateProductApi:
          Type: Api
          Properties:
            Path: /products
            Method: post
            RestApiId: !Ref CampusConnectApi
            Auth:
              Authorizer: JWTAuth
        UpdateProductApi:
          Type: Api
          Properties:
            Path: /products/{id}
            Method: put
            RestApiId: !Ref CampusConnectApi
            Auth:
              Authorizer: JWTAuth
        DeleteProductApi:
          Type: Api
          Properties:
            Path: /products/{id}
            Method: delete
            RestApiId: !Ref CampusConnectApi
            Auth:
              Authorizer: JWTAuth

  # Cart Function - handles all /cart/* routes
  CartFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub campus-connect-cart-${Environment}
      CodeUri: src/functions/cart/
      Handler: index.handler
      Layers:
        - !Ref SharedLayer
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref CartsTable
        - DynamoDBReadPolicy:
            TableName: !Ref ProductsTable
      Events:
        GetCartApi:
          Type: Api
          Properties:
            Path: /cart
            Method: get
            RestApiId: !Ref CampusConnectApi
            Auth:
              Authorizer: JWTAuth
        AddToCartApi:
          Type: Api
          Properties:
            Path: /cart
            Method: post
            RestApiId: !Ref CampusConnectApi
            Auth:
              Authorizer: JWTAuth
        AddToCartAltApi:
          Type: Api
          Properties:
            Path: /cart/add
            Method: post
            RestApiId: !Ref CampusConnectApi
            Auth:
              Authorizer: JWTAuth
        UpdateCartItemApi:
          Type: Api
          Properties:
            Path: /cart/{id}
            Method: put
            RestApiId: !Ref CampusConnectApi
            Auth:
              Authorizer: JWTAuth
        RemoveFromCartApi:
          Type: Api
          Properties:
            Path: /cart/{id}
            Method: delete
            RestApiId: !Ref CampusConnectApi
            Auth:
              Authorizer: JWTAuth
        RemoveFromCartAltApi:
          Type: Api
          Properties:
            Path: /cart/remove/{id}
            Method: delete
            RestApiId: !Ref CampusConnectApi
            Auth:
              Authorizer: JWTAuth
        ClearCartApi:
          Type: Api
          Properties:
            Path: /cart/clear
            Method: delete
            RestApiId: !Ref CampusConnectApi
            Auth:
              Authorizer: JWTAuth

  # Orders Function - handles all /orders/* routes
  OrdersFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub campus-connect-orders-${Environment}
      CodeUri: src/functions/orders/
      Handler: index.handler
      Layers:
        - !Ref SharedLayer
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref OrdersTable
        - DynamoDBReadPolicy:
            TableName: !Ref ProductsTable
        - DynamoDBReadPolicy:
            TableName: !Ref CartsTable
        - DynamoDBReadPolicy:
            TableName: !Ref UsersTable
      Events:
        CreateOrderApi:
          Type: Api
          Properties:
            Path: /orders
            Method: post
            RestApiId: !Ref CampusConnectApi
            Auth:
              Authorizer: JWTAuth
        RequestOrderApi:
          Type: Api
          Properties:
            Path: /orders/request
            Method: post
            RestApiId: !Ref CampusConnectApi
            Auth:
              Authorizer: JWTAuth
        GetOrdersApi:
          Type: Api
          Properties:
            Path: /orders
            Method: get
            RestApiId: !Ref CampusConnectApi
            Auth:
              Authorizer: JWTAuth
        GetMyOrdersApi:
          Type: Api
          Properties:
            Path: /orders/my-orders
            Method: get
            RestApiId: !Ref CampusConnectApi
            Auth:
              Authorizer: JWTAuth
        GetOrderApi:
          Type: Api
          Properties:
            Path: /orders/{id}
            Method: get
            RestApiId: !Ref CampusConnectApi
            Auth:
              Authorizer: JWTAuth
        UpdateOrderStatusApi:
          Type: Api
          Properties:
            Path: /orders/{id}/status
            Method: put
            RestApiId: !Ref CampusConnectApi
            Auth:
              Authorizer: JWTAuth

  # Admin Function - handles all /admin/* and /categories/* routes
  AdminFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub campus-connect-admin-${Environment}
      CodeUri: src/functions/admin/
      Handler: index.handler
      Layers:
        - !Ref SharedLayer
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref ProductsTable
        - DynamoDBCrudPolicy:
            TableName: !Ref CategoriesTable
        - DynamoDBCrudPolicy:
            TableName: !Ref SubcategoriesTable
        - DynamoDBCrudPolicy:
            TableName: !Ref UsersTable
      Events:
        GetSellerProductsApi:
          Type: Api
          Properties:
            Path: /admin/products
            Method: get
            RestApiId: !Ref CampusConnectApi
            Auth:
              Authorizer: JWTAuth
        GetSellerProductsByIdApi:
          Type: Api
          Properties:
            Path: /products/seller/{id}
            Method: get
            RestApiId: !Ref CampusConnectApi
            Auth:
              Authorizer: JWTAuth
        SeedCategoriesApi:
          Type: Api
          Properties:
            Path: /admin/seed/categories
            Method: post
            RestApiId: !Ref CampusConnectApi
            Auth:
              Authorizer: JWTAuth
        SeedSubcategoriesApi:
          Type: Api
          Properties:
            Path: /admin/seed/subcategories
            Method: post
            RestApiId: !Ref CampusConnectApi
            Auth:
              Authorizer: JWTAuth
        CleanDuplicatesApi:
          Type: Api
          Properties:
            Path: /admin/clean-duplicates
            Method: post
            RestApiId: !Ref CampusConnectApi
            Auth:
              Authorizer: JWTAuth
        MakeAdminApi:
          Type: Api
          Properties:
            Path: /admin/make-admin
            Method: post
            RestApiId: !Ref CampusConnectApi
            Auth:
              Authorizer: JWTAuth
        # Category management routes
        GetCategoriesApi:
          Type: Api
          Properties:
            Path: /categories
            Method: get
            RestApiId: !Ref CampusConnectApi
        CreateCategoryApi:
          Type: Api
          Properties:
            Path: /categories
            Method: post
            RestApiId: !Ref CampusConnectApi
            Auth:
              Authorizer: JWTAuth
        GetSubcategoriesApi:
          Type: Api
          Properties:
            Path: /subcategories
            Method: get
            RestApiId: !Ref CampusConnectApi
        CreateSubcategoryApi:
          Type: Api
          Properties:
            Path: /subcategories
            Method: post
            RestApiId: !Ref CampusConnectApi
            Auth:
              Authorizer: JWTAuth
        GetCategorySubcategoriesApi:
          Type: Api
          Properties:
            Path: /categories/{categoryId}/subcategories
            Method: get
            RestApiId: !Ref CampusConnectApi

  # Upload Function - handles all /upload/* routes
  UploadFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub campus-connect-upload-${Environment}
      CodeUri: src/functions/upload/
      Handler: getUploadUrl.handler
      Layers:
        - !Ref SharedLayer
      Policies:
        - S3CrudPolicy:
            BucketName: !Ref UploadsBucket
      Events:
        GetUploadUrlApi:
          Type: Api
          Properties:
            Path: /upload/url
            Method: post
            RestApiId: !Ref CampusConnectApi
            Auth:
              Authorizer: JWTAuth
        GetRegistrationUploadUrlApi:
          Type: Api
          Properties:
            Path: /upload/registration/url
            Method: post
            RestApiId: !Ref CampusConnectApi

  # =========================
  # INFRASTRUCTURE RESOURCES
  # =========================

  # DynamoDB Tables
  UsersTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub Users-${Environment}
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
        - AttributeName: email
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      GlobalSecondaryIndexes:
        - IndexName: EmailIndex
          KeySchema:
            - AttributeName: email
              KeyType: HASH
          Projection:
            ProjectionType: ALL

  ProductsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub Products-${Environment}
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
        - AttributeName: sellerId
          AttributeType: S
        - AttributeName: category
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      GlobalSecondaryIndexes:
        - IndexName: SellerIndex
          KeySchema:
            - AttributeName: sellerId
              KeyType: HASH
          Projection:
            ProjectionType: ALL
        - IndexName: CategoryIndex
          KeySchema:
            - AttributeName: category
              KeyType: HASH
          Projection:
            ProjectionType: ALL

  OrdersTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub Orders-${Environment}
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
        - AttributeName: userId
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      GlobalSecondaryIndexes:
        - IndexName: UserIndex
          KeySchema:
            - AttributeName: userId
              KeyType: HASH
          Projection:
            ProjectionType: ALL

  CartsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub Carts-${Environment}
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: userId
          AttributeType: S
      KeySchema:
        - AttributeName: userId
          KeyType: HASH

  CategoriesTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub Categories-${Environment}
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH

  SubcategoriesTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub Subcategories-${Environment}
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
        - AttributeName: categoryId
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      GlobalSecondaryIndexes:
        - IndexName: CategoryIndex
          KeySchema:
            - AttributeName: categoryId
              KeyType: HASH
          Projection:
            ProjectionType: ALL

  # S3 Bucket for uploads
  UploadsBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub campus-connect-uploads-${Environment}
      PublicAccessBlockConfiguration:
        BlockPublicAcls: false
        BlockPublicPolicy: false
        IgnorePublicAcls: false
        RestrictPublicBuckets: false
      CorsConfiguration:
        CorsRules:
          - AllowedHeaders: ['*']
            AllowedMethods: [GET, PUT, POST, DELETE, HEAD]
            AllowedOrigins: ['*']

  # JWT Secret in Secrets Manager
  JWTSecret:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: !Sub campus-connect-jwt-secret-${Environment}
      Description: JWT Secret for Campus Connect
      GenerateSecretString:
        SecretStringTemplate: '{}'
        GenerateStringKey: 'secret'
        PasswordLength: 64
        ExcludeCharacters: '"@/\'

  # API Gateway
  CampusConnectApi:
    Type: AWS::Serverless::Api
    Properties:
      Name: !Sub campus-connect-api-${Environment}
      StageName: !Ref Environment
      Cors:
        AllowMethods: "'*'"
        AllowHeaders: "'*'"
        AllowOrigin: "'*'"
        MaxAge: "'86400'"
      GatewayResponses:
        DEFAULT_4XX:
          ResponseParameters:
            Headers:
              Access-Control-Allow-Origin: "'*'"
              Access-Control-Allow-Headers: "'*'"
              Access-Control-Allow-Methods: "'*'"
        DEFAULT_5XX:
          ResponseParameters:
            Headers:
              Access-Control-Allow-Origin: "'*'"
              Access-Control-Allow-Headers: "'*'"
              Access-Control-Allow-Methods: "'*'"
      Auth:
        Authorizers:
          JWTAuth:
            FunctionArn: !GetAtt JWTAuthorizer.Arn
            AuthorizerPayloadFormatVersion: "1.0"
            Identity:
              Headers:
                - Authorization
            AuthorizerResultTtlInSeconds: 0

Outputs:
  ApiEndpoint:
    Description: API Gateway endpoint URL
    Value: !Sub "https://${CampusConnectApi}.execute-api.${AWS::Region}.amazonaws.com/${Environment}"
    Export:
      Name: !Sub "${AWS::StackName}-ApiEndpoint"

  UsersTableName:
    Description: Users DynamoDB table name
    Value: !Ref UsersTable

  ProductsTableName:
    Description: Products DynamoDB table name
    Value: !Ref ProductsTable

  UploadsBucketName:
    Description: S3 bucket for uploads
    Value: !Ref UploadsBucket
